# Generated by Django 3.1.4 on 2021-01-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=100000)),
                ('author', models.CharField(max_length=50)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
